name: Guilds
version: ${project.version}
main: me.glaremasters.guilds.Guilds
authors: [blockslayer22]
depend: [Vault]
softdepend: [MVdWPlaceholderAPI]
description: Guilds
website: https://glaremasters.me/discord
