name: Guilds
version: ${project.version}
main: me.glaremasters.guilds.Guilds
authors: [blockslayer22]
softdepend: [Vault, MVdWPlaceholderAPI, WorldGuard]
description: Guilds
website: https://glaremasters.me/discord
