name: Guilds
version: ${project.version}
main: me.glaremasters.guilds.Guilds
authors: [blockslayer22]
softdepend: [Vault, MVdWPlaceholderAPI, WorldGuard, PlaceholderAPI]
description: Guilds
website: https://glaremasters.me/discord

permissions:
  groups.group.member:
    children:
      guilds.command.create: true
      guilds.command.confirm: true
      guilds.command.cancel: true
      guilds.command.sethome: true
      guilds.command.delhome: true
      guilds.command.home: true
      guilds.command.rename: true
      guilds.command.chat: true
      guilds.command.status: true
      guilds.command.prefix: true
      guilds.command.invite: true
      guilds.command.upgrade: true
      guilds.command.transfer: true
      guilds.command.leave: true
      guilds.command.list: true
      guilds.command.info: true
      guilds.command.delete: true
      guilds.command.decline: true
      guilds.command.boot: true
      guilds.command.demoted: true
      guilds.command.promote: true
      guilds.command.accept: true
      guilds.command.check: true
      guilds.command.request: true
      guilds.command.buff: true
      guilds.command.help: true
      guilds.command.claim: true
      guilds.command.unclaim: true
      guilds.command.bank: true
      guilds.command.ally: true
    default: true

